### ISSUE TITLE
API error handling ignores errors in results

### ISSUE THREAD

**Issue by danmcp** [instructlab/eval#39]
When mt_bench gets an error in an openai call, the current logic is to retry a few times before returning $ERROR and a score of -1.  I am not sure what lm_eval is doing for mmlu yet.  The -1 score is later filtered out completely from the results.  Speaking for mt_bench and mt_bench_branch, this results in only partial results in the eval but that isn't conveyed to the user.

Potential Options to Fix:
- Fail on any api error
- Show the error rate in the results so the user can make a call on whether it's meaningful to them
- Allow user to specify an acceptable error rate

**Comment by xukai92** [comment]
it's a known issue to us as well.
- for now, for MT-Bench, we do the same thing (filtering out the -1 score) when computing the average. it's okay because, if it's a random API error, the average score is still unbiased (but more noise)
- for this reason, we did track the error rates so that we know how noisy the average score is
- perhaps a better way is to at least try a few times (if there is stochasticity in either the answer generation or teacher judgment) until we get something that is not `-1`
- as for MT-Bench-Branch, as the users would like to know the actual per `qna.yaml` score, it's probably more important to get at least 1 score that is not `-1`. 

as it's on our radar anyway, i can actually take a stab to see why there is `-1` and how to make sure we can get at least one meaningful score per Q&A

**Comment by danmcp** [comment]
> i can actually take a stab to see why there is `-1` and how to make sure we can get at least one meaningful score per Q&A

The most common errors I am seeing are hitting the 4096 context length limit.  I haven't had a chance to see if the issue is the model or vllm in my case.  When trying to increase the limit with vllm, it errors saying the max is 4096.

**Comment by danmcp** [comment]
This is the error vllm gives if you set the context larger than the model supports: ValueError: User-specified max_model_len (5000) is greater than the derived max_model_len (max_position_embeddings=4096 or model_max_length=None in model's config.json). This may lead to incorrect model outputs or CUDA errors. Make sure the value is correct and within the model context size.

Setting max_position_embeddings in the model config does get past the error but obviously results are no longer reliable.  This is probably acceptable for testing but it's not a great experience for the user just trying things out.

**Comment by danmcp** [comment]
Related: https://github.com/instructlab/instructlab/pull/1615

**Comment by danmcp** [comment]
Resolved with https://github.com/instructlab/eval/pull/49 and https://github.com/instructlab/instructlab/pull/1597
